run:
	python3 VMTranslator.py MemoryAccess/BasicTest/BasicTest.vm > MemoryAccess/BasicTest/BasicTest.asm
	python3 VMTranslator.py MemoryAccess/PointerTest/PointerTest.vm > MemoryAccess/PointerTest/PointerTest.asm 
	python3 VMTranslator.py MemoryAccess/StaticTest/StaticTest.vm > MemoryAccess/StaticTest/StaticTest.asm
	python3 VMTranslator.py StackArithmetic/SimpleAdd/SimpleAdd.vm > StackArithmetic/SimpleAdd/SimpleAdd.asm
	python3 VMTranslator.py StackArithmetic/StackTest/StackTest.vm > StackArithmetic/StackTest/StackTest.asm

