
run:
	python3 VMTranslator.py ProgramFlow/BasicLoop/BasicLoop.vm > ProgramFlow/BasicLoop/BasicLoop.asm
	python3 VMTranslator.py ProgramFlow/FibonacciSeries/FibonacciSeries.vm > ProgramFlow/FibonacciSeries/FibonacciSeries.asm
	python3 VMTranslator.py FunctionCalls/SimpleFunction/SimpleFunction.vm > FunctionCalls/SimpleFunction/SimpleFunction.asm
	python3 VMTranslator.py FunctionCalls/NestedCall > FunctionCalls/NestedCall/NestedCall.asm
	python3 VMTranslator.py FunctionCalls/FibonacciElement/ > FunctionCalls/FibonacciElement/FibonacciElement.asm
	python3 VMTranslator.py FunctionCalls/StaticsTest > FunctionCalls/StaticsTest/StaticsTest.asm 
